# Generated by Django 2.0.6 on 2018-07-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180704_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avr_score',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
