# Generated by Django 2.0.6 on 2018-07-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180705_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avr_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
