# Generated by Django 2.0.6 on 2018-07-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
