# Generated by Django 2.0.6 on 2018-07-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180710_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
